/**
 * AI Task Taxonomy & Capability Definitions (Phase 05)
 */

export const AI_TASK_TYPES = {
  GENERAL_CHAT: 'general_chat',
  PEDAGOGICAL_EXPLANATION: 'pedagogical_explanation',
  SYLLABUS_GENERATION: 'syllabus_generation',
  KNOWLEDGE_RELEVANCE_CLASSIFICATION: 'knowledge_relevance_classification',
  KNOWLEDGE_EVENT_EXTRACTION: 'knowledge_event_extraction',
};

export const AI_CAPABILITIES = {
  TEXT_GENERATION: 'text_generation',
  STRUCTURED_OUTPUT: 'structured_output',
  FAST_CLASSIFICATION: 'fast_classification',
  COMPLEX_REASONING: 'complex_reasoning',
};

export const TASK_CAPABILITY_REQUIREMENTS = {
  [AI_TASK_TYPES.GENERAL_CHAT]: [AI_CAPABILITIES.TEXT_GENERATION],
  [AI_TASK_TYPES.PEDAGOGICAL_EXPLANATION]: [AI_CAPABILITIES.TEXT_GENERATION, AI_CAPABILITIES.COMPLEX_REASONING],
  [AI_TASK_TYPES.SYLLABUS_GENERATION]: [AI_CAPABILITIES.STRUCTURED_OUTPUT, AI_CAPABILITIES.COMPLEX_REASONING],
  [AI_TASK_TYPES.KNOWLEDGE_RELEVANCE_CLASSIFICATION]: [AI_CAPABILITIES.FAST_CLASSIFICATION, AI_CAPABILITIES.STRUCTURED_OUTPUT],
  [AI_TASK_TYPES.KNOWLEDGE_EVENT_EXTRACTION]: [AI_CAPABILITIES.STRUCTURED_OUTPUT, AI_CAPABILITIES.COMPLEX_REASONING],
};

export function isValidTaskType(task) {
  return Object.values(AI_TASK_TYPES).includes(task);
}
